### ISSUE TITLE
How to add a one-time expense to the invoice?

### ISSUE THREAD

**Issue by mikemarsian** [nicholaspufal/invoice_creator#10]
I didn't find a example of how to do it in the readme.

**Comment by nicholaspufal** [comment]
Hey @mikemarsian, for some reason I was not getting notifications for this repo 🤔 

It's not in the README but if you run `invoice_creator --help` you will see it described in there:
```
Commands:
  invoice_creator create HOURS [EXPENSES_AMOUNT] --number=NUMBER  # Generates an invoice for the given amount of HOURS
  invoice_creator help [COMMAND]                                  # Describe available commands or one specific command
```

Providing that optional parameter will result in an extra line being displayed in the invoice with the title "Expenses"

**Comment by nicholaspufal** [comment]
https://github.com/nicholaspufal/invoice_creator/commit/e5b1a1825ad0395736b554621c1f2f56d22e1225

Thanks for the feedback :)
